sudo: required

language: python

env:
  matrix:
    - DISTRIB="neurodebian" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.5" NUMPY_VERSION="*" SCIPY_VERSION="*"
      SCIKIT_LEARN_VERSION="*" PANDAS_VERSION="*" MATPLOTLIB_VERSION="*"
      NETWORKX_VERSION="*"

virtualenv:
  system_site_packages: true

script:
    - make clean
    - make test-code

after_success:
    - |
      if [[ "$COVERAGE" == "true" ]]; then
          coveralls || echo "coverage upload failed"
      fi
